#!/usr/bin/env python3
"""Per-user title style memory loader.

We keep per-user title style instructions as plain text files so style can diverge
between users without changing code.

- Insurance agent titles are generated by InsuranceTitleGenerator (unchanged).
- Tech enthusiast titles can be generated by LLM using these instructions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional


_BASE_DIR = Path("/root/.openclaw/workspace/content-pipeline")
_STYLE_DIR = _BASE_DIR / "user_memory"
_GENERAL_TITLE = _STYLE_DIR / "general_non_insurance_title_style.md"


@dataclass
class TitleStyle:
    user_id: str
    instructions: str


def load_title_style(user_id: str) -> Optional[TitleStyle]:
    if not user_id:
        return None

    parts = []

    # 通用：除保险外其他用户共用
    if user_id != "insurance_agent" and _GENERAL_TITLE.exists():
        gt = _GENERAL_TITLE.read_text(encoding="utf-8").strip()
        if gt:
            parts.append(gt)

    # 专用：用户自己的覆盖/补充
    path = _STYLE_DIR / f"{user_id}_title_style.md"
    if path.exists():
        ut = path.read_text(encoding="utf-8").strip()
        if ut:
            parts.append(ut)

    if not parts:
        return None

    return TitleStyle(user_id=user_id, instructions="\n\n".join(parts))
