#!/usr/bin/env python3
"""Per-user title style memory loader.

We keep per-user title style instructions as plain text files so style can diverge
between users without changing code.

- Insurance agent titles are generated by InsuranceTitleGenerator (unchanged).
- Tech enthusiast titles can be generated by LLM using these instructions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional


_BASE_DIR = Path("/root/.openclaw/workspace/content-pipeline")
_STYLE_DIR = _BASE_DIR / "user_memory"


@dataclass
class TitleStyle:
    user_id: str
    instructions: str


def load_title_style(user_id: str) -> Optional[TitleStyle]:
    if not user_id:
        return None

    path = _STYLE_DIR / f"{user_id}_title_style.md"
    if not path.exists():
        return None

    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return None

    return TitleStyle(user_id=user_id, instructions=text)
